language: node_js
node_js:
- '0.12'
sudo: false
after_success:
- gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: hN0LuefEnbSYTLDgCWRLq2H9e4sQ+rDcSthPUoyOVPMp16WDccFKGXm9uIFLQ3GrNr4aDBoEGXRSfdC5KJsDrqeoJtU0za+Xpm3U+pzOYJeqwo+1N1bd+GiCtxI75pbbGCdGhl75WKLUTpR2pf5hddzRKxbohW61xGF0FRXhRXc=
  on:
    tags: true
