language: node_js
node_js:
  - '0.12'
sudo: false
after_success:
  - gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 8660......1b53
    secure: iCRiG/ZNnWjKz1E3oV87GYvH6ns6HtBzFNvWXz6T+7ZT28kYEu1Fy61FpCgwrjLOvW5kyJLgY0qSSAxLdPBE2/ipyJtSUVK++VEj1ahNO5AiBDCv4GOxv7vC+Q/Z3KjaqVmfef7SuPyN+2kYTlgFrcVXMf1QGBeD3rWE/bMq5sM=
  on:
    tags: true
